language: node_js
node_js:
   - "node"
cache: npm
services:
  - postgresql
before_script:
  - psql -c 'createdb travis_ci_test;' -U postgres
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - pg

env:
  global:
  - PGPORT=5433
  - NODE_ENV=test
  - TEST_DATABASE_URL=postgresql://mikeogu:misha007@localhost:5433/sendit_test_db
