language: node_js
node_js:
   - "node"
cache: npm
services:
  - postgresql
before_script:
  - sleep 15
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
  - PGPORT=5433
  - NODE_ENV=test

