language: node_js
node_js:
   - "node"
cache: npm
services:
  - postgresql
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
  - PGPORT=5432
  - NODE_ENV=test

